-- SF Symbols
return {
  apple            = "􀣺",
  sun              = "􀆮",
  moon             = "􀆺",
  wifi             = "􀙇",
  network          = "􀤆",
  speed            = "􀍾",
  battery_100      = "􀛨",
  battery_75       = "􀺸",
  battery_50       = "􀺶",
  battery_25       = "􀛩",
  battery_0        = "􀛪",
  battery_charging = "􀢋",
  music_play       = "􀑪",
  music_pause      = "􀑛",
  volume_high      = "􀊩",
  volume_mid       = "􀊧",
  volume_low       = "􀊥",
  volume_off       = "􀊣",
}
