#!/usr/bin/env lua

package.cpath = package.cpath .. ";" .. os.getenv("HOME") .. "/.local/share/sketchybar_lua/?.so"

local config_dir = os.getenv("HOME") .. "/.config/sketchybar"
package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path

require("init")
